export { default as registerCommands } from "./helpers/registerCommands"

export { default as ping } from "./commands/ping"
export { default as dice } from "./commands/dice"
export { default as apexStats } from "./commands/apexStats"
export { default as apexLink } from "./commands/apexLink"
export { default as apexUnlink } from "./commands/apexUnlink"
export { default as setupRoles } from "./commands/setupRoles"
export { default as coin } from "./commands/coin"
export { default as balance } from "./commands/balance"
export { default as grant } from "./commands/grant"
export { default as balanceTransfer } from "./commands/balanceTransfer"